[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci --production=false"]

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "cd backend && npm start"
